name: Jira Create issue
description: Create a new Jira issue
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  jiraBaseUrl:
    description: Jira base url
    required: true
  project:
    description: Key of the project
    required: true
  issuetype:
    description: "Type of the issue to be created. Example: 'Incident'"
    required: true
  summary:
    description: Issue summary
    required: true
  description:
    description: Issue description
    required: false
  label:
    description: Label
  jiraEmail:
    description: Jira email
    required: true
  jiraToken:
    description: Jira token
    required: true
outputs:
  issue:
    description: Key of the newly created issue
runs:
  using: 'node12'
  main: './dist/index.js'
